name: "Static Analysis"

on:
    push:
        branches:
            - "main"
    pull_request: null
    schedule:
        # Do not make it the first of the month and/or midnight since it is a very busy time
        - cron: "* 10 5 * *"

jobs:
    tests:
        runs-on: "ubuntu-latest"
        name: "Psalm ${{ matrix.php }}"
        strategy:
            fail-fast: true
            matrix:
                php:
                    - "8.2"

        steps:
            -   name: "Check out repository code"
                uses: "actions/checkout@v2"

            -   name: "Setup PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php }}"
                    tools: "composer"
                    coverage: "pcov"

            -   name: "Install Composer dependencies"
                uses: "ramsey/composer-install@v2"

            -   name: "Install Psalm Composer dependencies"
                if: "! matrix.skip_static_checks"
                uses: "ramsey/composer-install@v2"
                with:
                    working-directory: "vendor-bin/psalm"

            -   name: "Run Psalm"
                run: "make psalm"
